### PR TITLE
Added STRING_REPORT_TEXT to enUS localization table

### PR DESCRIPTION
**Pull request by spencerneutron**
This localization string is only used at frames/window_breakdown/window_playerbreakdown_spells.lua:642

It looks like it may have been missed, but was mentioned in a comment left on commit cd8266f

Other locales may need this string as well, but I'm not comfortable suggesting other translations. 

May contribute to issue #701

### CODE REVIEW

**Comment by spencerneutron** [comment]
Also to document, this is throwing a lua error in-game as the Loc table is not using the silent flag.

I believe this would partially resolve #701

**Comment by spencerneutron** [comment]
> Localization is stored and updated in curseforge.

Apologies, I didn't know that.

This still throws lua errors when using outside of curseforge and should be included in the source like the other strings. There is _no value_ for this key currently in enUS.

**Comment by Flamanis** [comment]
I just fetch the latest localization from the latest curseforge version when the need arises

**Comment by Tercioo** [comment]
Did a double check, this string is registered in the curseforge localization.

**Pull request closed without merging**
