### PR TITLE
Add Github workflow to automatically package addon on tag push

### PR DESCRIPTION
**Pull request by faku99**
This pull request aims at allowing WowUp users to install Details by using the "Install from URL" feature.

My changes simply add the `.github/workflows/release.yml` file. This file sets up a Github workflow using the [BigWigsMods/packager@v2](https://github.com/BigWigsMods/packager) action.
This workflow action generates an addon `.zip` file from a repository. It automatically triggers when a new tag has been pushed. To communicate with addon providers (*i.e.* Curseforge), it needs an API token. This token should be added as a *secret* of this repository, under the name `CF_API_KEY`.

I made some tests on my forked repository but I could not test communication with CurseForge API since my CurseForge account does not have permissions to manage the Details project. Anyway, once you set the `CF_API_KEY` secret, everything should work out of the box.
However I still recommend you to create a new branch in order to test things up before merging on the `master` branch. Moreover, it is possible to automatically upload the new package via the CurseForge API so that users have access to the new version on tag push. Right now, I disabled the upload to CurseForge in order to avoid publishing possibly-corrupted `.zip` files.

### CODE REVIEW

**Comment by KDederichs** [comment]
Quick note:
I think it's actually missing handling the plugins that come with details (located in the plugins folder in the Repo).

You'd probably have to do something like:
```
            - name: Make Release Folder
              run: mkdir ../release
            - name: Move Plugins
              run: |
                mv plugins/Details_DataStorage ../release/Details_DataStorage
                mv plugins/Details_EncounterDetails ../release/Details_EncounterDetails
                mv plugins/Details_RaidCheck ../release/Details_RaidCheck
                mv plugins/Details_Streamer ../release/Details_Streamer
                mv plugins/Details_TinyThreat ../release/Details_TinyThreat
                mv plugins/Details_Vanguard ../release/Details_Vanguard
                rm -rf plugins
            - name: Move Main Addon
              run: |
                mv ./* ../release/Details
            - name: Package and release classic
              uses: BigWigsMods/packager@v2
              env:
                GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
              with:
                args: -c -r ../release -t ../release

```

to accomodate for that (-c to don't copy stuff to release dir cause it's done already, -r and -t to set release and topdir to the new directory)

**Comment by QartemisT** [comment]
TIP: May want to use the `-S` parameter too, so that it does "multi-packager" building, and tags for ALL game versions that there are TOC's or `## Interface-TYPE` for :)

**Comment by Tercioo** [comment]
Thank you!
At the moment Details! is hosted on Wago and WowUp costumers can pull the addon from there.

**Comment by BoreasDragon** [comment]
Still having this issue and wago is only usable with wowup provided one enables data tracking and ad display.

**Pull request closed without merging**
