### PR TITLE
Support for Wrath of the Lich King Classic

### PR DESCRIPTION
**Pull request by BigBadBleuCheese**
There are still more errors to deal with, but here's what I've figured out thus far. It's now at least drawing the meter and updating it.

### CODE REVIEW

**Comment by BigBadBleuCheese** [comment]
Trying to root this one out at the moment. Happens at startup.

```
Message: Interface\AddOns\Details\functions\spellcache.lua:149: attempt to concatenate a nil value
Time: Wed Jul 20 12:30:32 2022
Count: 1
Stack: Interface\AddOns\Details\functions\spellcache.lua:149: attempt to concatenate a nil value
[string "@Interface\AddOns\Details\functions\spellcache.lua"]:149: in main chunk

Locals: _detalhes = <table> {
 ToK0Min = <function> defined @Interface\AddOns\Details\core\util.lua:602
 APITopics = <table> {
 }
 GetSpellSchoolColor = <function> defined @Interface\AddOns\Details\functions\spells.lua:3240
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 GetEncounterIdFromBossIndex = <function> defined @Interface\AddOns\Details\functions\boss.lua:104
 hex = <function> defined @Interface\AddOns\Details\core\util.lua:899
 LowerizeKeys = <function> defined @Interface\AddOns\Details\core\util.lua:350
 debug = false
 habilidade_e_energy = <table> {
 }
 dont_open_news = true
 CopyTable = <function> defined @Interface\AddOns\Details\boot.lua:891
 SendHighFive = <function> defined @Interface\AddOns\Details\boot.lua:748
 IsInInstance = <function> defined @Interface\AddOns\Details\functions\boss.lua:12
 ClearSpellCache = <function> defined @Interface\AddOns\Details\functions\spellcache.lua:63
 icon_animations = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 FindGUIDFromName = <function> defined @Interface\AddOns\Details\core\util.lua:1155
 alvo_da_habilidade = <table> {
 }
 RestoreState_CurrentMythicDungeonRun = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1518
 APIVersion = 146
 GetEncounterStartInfo = <function> defined @Interface\AddOns\Details\functions\boss.lua:109
 GetEncounterEnd = <function> defined @Interface\AddOns\Details\functions\boss.lua:125
 ImportProfile = <function> defined @Interface\AddOns\Details\functions\profiles.lua:1677
 OnCombatPhaseChanged = <function> defined @Interface\AddOns\Details\functions\bossmods.lua:6
 SetNickname = <function> defined @Interface\AddOns\Details\Libs\NickTag-1.0\NickTag-1.0.lua:573
 UnregisterAllComm = <function> defined @Interface\AddOns\Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 default_global_data = <table> {
 }
 bcc_counter = 41
 name_space = <function> defined @Interface\AddOns\Details\core\util.lua:1601
 combate = <table> {
 }
 gump = <table> {
 }
 cache_npc_ids = <table> {
 }
 GetCurrentDungeonBossListFromEJ = <function> defined @Interface\AddOns\Details\functions\boss.lua:339
 GetCLName = <function> defined @Interface\AddOns\Details\functions\classes.lua:132
 GetCurrentToKFunction = <function> defined @Interface\AddOns\Details\core\util.lua:675
 NewModule = <function> defined @Interface\AddOns\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetFlag = <function> defined @Interface\AddOns\Details\functions\classes.lua:150
 InstancesToStoreData = <table> {
 }
 RunCodeTypes = <table> {
 }
 name_space_info = <function> defined @Interface\AddOns\Details\core\util.lua:1610
 ShowDelayMsg = <function> defined @Interface\AddOns\Details\boot.lua:910
 RegistredEvents = <table> {
 }
 Deserialize = <function> defined @Interface\AddOns\Details\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 HealthTick = <function> defined @Interface\AddOns\Details\core\util.lua:1086
 GetSpellSchoolFormatedName = <function> defined @Interface\AddOns\Details\functions\spells.lua:3236
 realversion = 146
 GetEncounterSpells = <function> defined @Interface\AddOns\Details\functions\boss.lua:166
 default_skin_to_use = "Minimalistic"
 trim = <function> defined @Interface\AddOns\Details\core\util.lua:948
 GetEncounterEqualize = <function> defined @Interface\AddOns\Details\functions\boss.lua:142
 name = "_detalhes"
 role_texcoord = <table> {
 }
 PlayerDetailsWindow = DetailsPlayerDetailsWindow {
 }
 GetNumer
```

**Comment by BigBadBleuCheese** [comment]
Actually, nevermind that last. Looks like I made a mistake in my environment.

**Comment by BigBadBleuCheese** [comment]
Wow, okay, can't find any more errors!

**Comment by Flamanis** [comment]
Apologies for not seeing this sooner. The repository is currently working with Wrath minus Streamer and a few of the other plugins. We have access now to test and I've been on it lately helping as many as I can get themselves up and running. Thank you for this. All will be resolved soon :)

**Review by Tercioo — APPROVED** [review]

**Comment by BigBadBleuCheese** [comment]
Oops, looks like I have some conflicts to resolve. I'll get on that if you want?

**Comment by Tercioo** [comment]
> Oops, looks like I have some conflicts to resolve. I'll get on that if you want?

no no, I think the fix i've just sent is the same thing written differently:

	if (not (DetailsFramework.IsTBCWow() or DetailsFramework.IsWotLKWow())) then
=======
	if (not DetailsFramework.IsTBCWow() and not DetailsFramework.IsWotLKWow()) then

**Review by Tercioo — APPROVED** [review]

**Review by Tercioo — APPROVED** [review]

**Comment by BigBadBleuCheese** [comment]
> > Oops, looks like I have some conflicts to resolve. I'll get on that if you want?
> 
> no no, I think the fix i've just sent is the same thing written differently:
> 
> ```
> if (not (DetailsFramework.IsTBCWow() or DetailsFramework.IsWotLKWow())) then
> ```
> 
> ======= if (not DetailsFramework.IsTBCWow() and not DetailsFramework.IsWotLKWow()) then

Yeah, it is the same in essence of logic (see: https://en.wikipedia.org/wiki/De_Morgan%27s_laws), but _not p and not q_ is less efficient than _not (p or q)_. It's the kind of thing a compiler optimizer changes. Please forgive the CS professor that lives in my head and heaves textbooks at people unsolicited.

**Review by Tercioo — APPROVED** [review]

**Comment by Flamanis** [comment]
I always forget De Morgans law when dealing with bools. Honestly, you are correct about optimization, but it is no noticeable difference in execution performance.

**Pull request merged**
