### PR TITLE
Fix Spell Reflection Tracking

### PR DESCRIPTION
**Pull request by m4tjz**
Better tracking of Spell Reflected Damage.

### CODE REVIEW

**Comment by m4tjz** [comment]
Made an edit because of a typo when updating the file, oops.

**Comment by Tercioo** [comment]
Thank you, I'm scheduling to see/implement this next weekend on may 30.

**Comment by m4tjz** [comment]
You may want to change things on the code, on a second look it may not be necessary to try to **nil** the **table serials** on lines **518**, **1533**, **1554**, **2580** and **2591** as the **_table_wipe** that starts at line **5372** should take care of them, right? Just pointing it out because as I said, I'm not the best at coding, less LUA.

**Comment by Tercioo** [comment]
Great implementation, thank you!
You're free to send more pull requests with fixes and more implementation. 

Maybe we don't need to use hardcoded spellIIds (reflection_spellid) since the parser can figure out using the Reflected miss type.

Well with time we can figure out how to improve the code.

**Pull request merged**
