### PR TITLE
Added training dummy IDs for Dornogal to window_scrolldamage.lua

### PR DESCRIPTION
**Pull request by Krytos**
Added training dummy IDs for Dornogal to window_scrolldamage.lua so it auto opens on targeting them.

### CODE REVIEW

**Comment by Tercioo** [comment]
Buddy, I think your software messed a lot with the document format, looks like there is a lot of spaces added. Could you just change the npcIds and nothing else? Or just post here the npcs to add and I can do it manually.

**Comment by Krytos** [comment]
Yep. Seems to have been my formatter. Did not even realize it. Sorry about that. 

This is the important part: 

```lua
[225983] = true, -- Dungeoneer's training dummy - Dornogal
[225984] = true, -- Normal dummy - Dornogal
[225979] = true, -- Healing Dummy - Dornogal
[225982] = true, -- Cleave Dummy - Dornogal
[225977] = true, -- Dungeoneer's Tanking dummy - Dornogal
[225976] = true, -- Normal Tanking dummy - Dornogal
```

I'll update the PR though.

**Comment by Krytos** [comment]
Fixed. I don't see the problem with proper formatting though. It's your project, so not gonna argue about it but just curious why the formatting was an issue. Was it simply because it makes it harder to see what changed at a glance?

**Comment by Tercioo** [comment]
Added manually, thank you!

**Pull request closed without merging**
