### PR TITLE
Change _ to nil

### PR DESCRIPTION
**Pull request by Flamanis**
Other addons will populate the global _ to be some random value. If it is not a string or nil, then the Auto Run Code window cannot be opened.

### CODE REVIEW

**Comment by Flamanis** [comment]
I went through the entire project and attempted to replace the _ variable in as many function calls as I could. This is so that random addons tainting the "global" _ variable, don't send garbage data to Details functions/UI elements.

I did a quick test with 90% of the UI elements, and none of them spit out any bugs. I went through and checked the diff and made sure that I had a 1/1 ratio of nil to _. I still recommend you check through the changes and see if any of the areas I messed with might have actually used the _ variable.

**Comment by Tercioo** [comment]
In the header of each file, there's a **local _** which make the underscore character be nil in the entire file.

**Comment by Flamanis** [comment]
Same bug is on tbc. I'll resubmit the pull request when i wake to be the
correct format for ya. Thats a much smarter route...

**Comment by Tercioo** [comment]
yeah, just add a the local _ in the beginning of each file that doesn't 
have it yet and it's good to go.

------ Original Message ------
From: "Flamanis" ***@***.***>
To: "Tercioo/Details-Damage-Meter" 
***@***.***>
Cc: "Tercio Jose" ***@***.***>; "Comment" 
***@***.***>
Sent: 23-May-21 12:31:01 PM
Subject: Re: [Tercioo/Details-Damage-Meter] Change _ to nil (#213)

>
>Same bug is on tbc. I'll resubmit the pull request when i wake to be 
>the
>correct format for ya. Thats a much smarter route...

**Pull request closed without merging**
