### PR TITLE
Added build workflow

### PR DESCRIPTION
**Pull request by caffeineaddiction**
These changes will allow for Github to Package your releases. It can also send new packages to:

Curseforge via CF_API_KEY: ${{ secrets.CF_API_KEY }}
WowInterface.com via WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
Wago.io via WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

please contact me on discord if you have questions: caffeineaddiction#8378

### CODE REVIEW

**Comment by caffeineaddiction** [comment]
Somehow I messed up Localization though ... assuming I didn't move a file to the correct location or something.  Not super familiar w/ Ace3Locale but im digging.

**Comment by Flamanis** [comment]
At this stage, with how many issues are in the pull request. My vote is a no.

**Comment by Tercioo** [comment]
It's a well done job, I believe you took several hours of your time doing this and I appreciate.
I saw you also are doing implementations on other addons like Grid2 and I can imagine how great are having a dedicated person like you on their project.
In Details! we already have a packager solution which work for us and adding yours above ours can and will cause issues which we cannot afford to have at the moment.
I'm archiving this pull request, we might need in the future, thank you!

**Comment by caffeineaddiction** [comment]
No worries, my main objective was to get it packaging on GitHub so that it can be used w/ CurseBreaker.  I accomplished that objective on my fork ... but @Flamanis is correct the translations cause many issues.  Hard coding it works for me in my fork ... but its far from the correct solution.  This pull request was more of an idea rather than a total solution.

**Pull request closed without merging**
