### PR TITLE
Move the LibOpenRaid failed loading message below the CanLoad check

### PR DESCRIPTION
**Pull request by Flamanis**

### CODE REVIEW

**Comment by Tercioo** [comment]
LIB_OPEN_RAID_CAN_LOAD is false by default.
If something bad happens on libStub:NewLibrary() in the main file, your change won't alert the user that something bad happened.

**Comment by Flamanis** [comment]
True. At the same time, CAN_LOAD and DATABASE_LOADED are currently always false on Wrath. So the message 100% pops up.

**Comment by Flamanis** [comment]
If you want, we can add the wrath version check beforehand.

**Comment by Tercioo** [comment]
You're right. Let's do this fix.

**Pull request merged**
