### PR TITLE
Fix talent display

### PR DESCRIPTION
**Pull request by ChrisKader**

### CODE REVIEW

**Comment by Tercioo** [comment]
Could you provide a screenshot of the bug you're having?

**Comment by Flamanis** [comment]
CoolTip:AddLine (leftText, rightText, frame, ColorR1, ColorG1, ColorB1, ColorA1, ColorR2, ColorG2, ColorB2, ColorA2, fontSize, fontFace, fontFlag)

This is the function header for the CoolTip AddLine function used by Details. As you can see, the two arguments be used are leftText and rightText. Which of course is different than the normal GameToolTip function. As Terciob mentioned, what problem are you trying to solve?

**Comment by ChrisKader** [comment]
image

**Comment by ChrisKader** [comment]
The proposed code fix does this:

image

**Comment by Flamanis** [comment]
Cannot reproduce. Talents display correctly on my end.

**Comment by Flamanis** [comment]
Wow_2022-10-05_01-07-22

**Comment by Flamanis** [comment]
I looked through all of the fonts/options for tooltips. The only thing that could make an icon go off the right is the 'text shadow' option. Try disabling that.

**Comment by Tercioo** [comment]
closed.

**Pull request closed without merging**
