### PR TITLE
Having TinyThreat actually respect the 'Show Percentage' toggle in op…

### PR DESCRIPTION
**Pull request by Chalos-Atiesh**
https://github.com/Tercioo/Details-Damage-Meter/issues/76

### CODE REVIEW

**Comment by Tercioo** [comment]
I'm not aware of an option called "Show Percent".

**Comment by Chalos-Atiesh** [comment]
It's here: [https://i.imgur.com/1sFRysj.jpg](https://i.imgur.com/1sFRysj.jpg)

**Comment by Chalos-Atiesh** [comment]
Any updates on this?

**Comment by Tercioo** [comment]
I was looking and I'm not sure where the value for ThreatMeterFrame.ShowPercentText is set in the threat frame, also there's no value set if the comparison turns to false (setting without the percent).

**Comment by Chalos-Atiesh** [comment]
I'm not really sure what else to say. I've tested it and it correctly hides the text values. If there's anything else I can provide please let me know.

**Pull request closed without merging**
