### PR TITLE
Add heoric and normal for raid data

### PR DESCRIPTION
**Pull request by jazz836062**

### CODE REVIEW

**Comment by Tercioo** [comment]
Hi, thank you for the patch, but I'm confused on what it is actually doing.
Could you tell more about what this patch brings to the addon?

**Comment by jazz836062** [comment]
Currently, you are storing Mythic pulls with best percent and such but not normal and heroic.  This patch adds normal and heroic to that tracking.  Functionally, it does the same as your raid_data.mythic_raid_data but for lower difficulties.

**Comment by jazz836062** [comment]
My reason for this was that I had made a WA to show Pull Count and Current Best Boss % for my stream.  It worked as is for mythic, but not for heroic and normal.

**Comment by jazz836062** [comment]
Is there still a issue with this?  I have several people that would like to use my custom WA and relies on this functionality.

**Pull request closed without merging**
